### PR TITLE
now using clientHeight to detect when to show/hide scrollbar

### PR DESCRIPTION
**Pull request by srobilliardfln**
This fixes an issue in IE 11 where the scrollbar is always showing, even when the height of the text area is less than the max height.
More specifically it seems that in IE11, the computed height from window.getComputedStyle is less than the actual height of the element. clientHeight appears to be a more reliable source for determining the height of the DOM element. This fixes issue #226

### CODE REVIEW

**Comment by srobilliardfln** [comment]
Hi there, 
hoping someone may be able to review my pull request? It's been a few months now.

**Comment by jackmoore** [comment]
@srobilliardfln Thanks for the pull request, my apologies for the late response.  At first glance this does not work as you cannot substitute style height for clientHeight, as clientHeight includes padding.  Your fix probably only worked for your specific CSS and would not be appropriate to merge into master.

I tested anyway and was not able to verify that it fixed anything.  I still get an IE11 scrollbar on the same instances as prior to incorporating your change.  But I was able to see that there is an issue and agree that it should be fixed.

**Comment by srobilliardfln** [comment]
Thanks for reviewing @jackmoore :+1:

**Comment by jackmoore** [comment]
Looks like this is a bug with how IE11 handles window.getComputedStyle; it does not account for changes to the box-sizing property.  I'm assuming you set your textarea box-sizing to `border-box`.  The default box-sizing would not be hit by this and hides scrollbars as expected.

**Comment by srobilliardfln** [comment]
Ahhh yes you are right. I will see if I can get back on master by removing that style.

**Comment by jackmoore** [comment]
See my referenced pull request for a potential fix.  It uses offsetHeight as a replacement for the computed style height for a border-box element.  This needs more testing because I'm unsure of the browser support range for offsetHeight.  Quick test showed it working in modern browsers.

**Comment by jackmoore** [comment]
It would probably be better form to add up the individual computed styles (height, paddingTop/Bottom, borderTopWidth/BottomWidth) rather than relying on offsetHeight, since it's just Working Draft. It would require adding in a test to see if the computed style for height is correct or not to determine if those additional styles should be added to the computed height or not.

**Pull request closed without merging**
