### PR TITLE
Rollback changes 

### PR DESCRIPTION
**Pull request by jpacareu-meli**
- Reverting changes inserted with this #384 because of this [comment](https://github.com/jackmoore/autosize/pull/384#issuecomment-842381899)

### CODE REVIEW

**Comment by jackmoore** [comment]
Done. Did this locally instead of merging to also set the version number in the distributables, but thank you!

**Comment by jpacareu-meli** [comment]
> Done. Did this locally instead of merging to also set the version number in the distributables, but thank you!

True, lot better, thanks Jack! 

Oh, btw you would be generating a tag for 4.0.4 right? or there is some sort of CI?

Cheers!

**Comment by jackmoore** [comment]
@jpacareu-meli I added the tag manually, but it should be available now as 4.0.4 and on NPM.

**Comment by jpacareu-meli** [comment]
> @jpacareu-meli I added the tag manually, but it should be available now as 4.0.4 and on NPM.

Yeah, that's what I thought but, maybe forgot tu push it or smt, cause I can't seem to find it 😅 

image

**Comment by jackmoore** [comment]
Thanks, went back and pushed the tags and published 4.0.4 on NPM. Should be available even if the NPM page doesn't show it as a version yet.

**Pull request closed without merging**
