### PR TITLE
fix scroll issues for textarea on divs with overflow

### PR DESCRIPTION
**Pull request by mst-avaleo**
The commit fixes scroll issues with textarea which are on a div with overflow. autosize is changing scrollTop of the parent div during update after text height. In result textarea is jumping when using is typing something in the field. The problem is significant for bigger texts.

### CODE REVIEW

**Comment by jacksondc** [comment]
It seems the compiled js didn't get committed (`dist/autosize.js` and `dist/autosize.min.js`). Hoping a fix for this issue gets merged soon!

**Comment by mst-avaleo** [comment]
I've added missing dist files. The fix works in our application pretty well. I'm also hoping for quick merge of the fix, since then I could remove fork from our app.

**Comment by jacksondc** [comment]
Thanks! That's working great for nested textareas, but it looks like it breaks when there is no parent with `overflow: auto` ("Uncaught TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'").

I think `findOverflowParent` might need to do something like this:

````js
while(element.parentNode) {
  element = element.parentNode;
  if(element === document) { // there is no overflow parent
    return null;
  } else {
    var elementStyle = window.getComputedStyle(element, null);
    var overflowValue = elementStyle.getPropertyValue('overflow-y');
    if (overflowValue === 'auto') {
      return element;
    }
  }
}
````

**Comment by mst-avaleo** [comment]
Ah, that's true. In our project we don't have this case. Here's a fix, similar to what you proposed.

**Comment by jacksondc** [comment]
I'm using the fork in my project too, now, and it's working great. Thanks @mst-avaleo!

**Comment by jackmoore** [comment]
Thanks @mst-avaleo.  My apologies for the late response to your pull request.  I think you did a good job, but there was a couple of things I wanted to do a little different. I committed an alternative fix for this using your code as a guide, let me know how it works for you.

**Comment by jackmoore** [comment]
I worried about the performance impact of calling getComputedStyle on every ancestor node, so I replaced that with just a check for the scrollTop value, since that was what was actually needed. Since changing the height of the textarea element may impact the overflow of more than one parent element, I changed it to restore the overflow for all ancestor elements (which removed the need to specifically target document.body).

**Comment by mst-avaleo** [comment]
It works like my fix, so I'll switch to official 3.0.16. Thanks for the final fix!

**Comment by jackmoore** [comment]
👍 Thank you

**Pull request closed without merging**
